### ISSUE TITLE
feature request: number of data packages uploaded to PASTA for a prescribed temporal range

### ISSUE THREAD

**Issue by srearl** [PASTAplus/counter#1]
Another helpful data point would be the number of packages with a given scope (or other parameter) for a prescribed time period.

**Comment by servilla** [comment]
To clarify, is this data point showing the number of data package uploaded to PASTA+ during a prescribed time period or the number of packages downloaded. If the later, is this more of the Zip archive you are referring to?

Thanks!

**Comment by servilla** [comment]
Clarification via a Slack conversation:

> 4:54 PM
> Stevan Earl Hi Mark - I am putting these data together and the file downloads across years (my unit of interest/measure) is great but was interested to overlay the number of packages available within a given time period (year in this case) as well. That was the GH issue. However, looking a bit closer it appears that at least one file from every data set, at least for the ranges I queried, was downloaded, in which case we can calculate the number of datasets in PASTA for a given range. These results, this one included, seem odd to me, I keep going back to possible bot activity, but I can at least get that metric of interest. Still, it might be useful to have a tool that can give a confirmed count of the number of datasets for a desired range.
> 4:56 PM
> Mark Servilla sorry for being obtuse, but are you saying the number of data packages available for download give a period of time? (edited) 
> 4:56 PM
> Stevan Earl exactly
> 4:57 PM
> Mark Servilla so that would be cumulative since earlier data packages would be available too, correct?
> 4:57 PM
> Stevan Earl yes, except in the very rare case that a dataset is deleted from pasta
> 4:58 PM
> Mark Servilla right

**Comment by servilla** [comment]
The current package list in the table seems to provide the list of all data packages available up through the end date specified.

There is an issue with identifying deleted (aka archived) data packages - these are not directly available during the processing to retrieve active data packages when using the *counter* PASTA API and therefore are basically ignored when counting entity downloads in the current code base. Albeit an important datum, there are few deleted data packages so the discrepancy in downloads is likely small. When using the database API in *counter*, this can be fixed simply by including deleted data packages in the SQL query (should they be identified as deleted in some way? - this would be a bit more costly). When using the default PASTA API in *counter*, more code modification is required to incorporate deleted data packages - this would have to be from a separate API call to PASTA (the get deleted data packages method).

**Comment by srearl** [comment]
Agreed. I was able to derive those values but was a bit uneasy about their accuracy/completeness given that this was not an explicit output, at least not that I was aware, of `counter`. Makes perfect sense, though, given that data files that were not downloaded (i.e., zero file count) are included in the results as well. Thanks for your help, @servilla, will close this issue.
