### ISSUE TITLE
Getting "pg_config executable not found" error when installing

### ISSUE THREAD

**Issue by mfrants** [PASTAplus/counter#3]
I currently have python 3.6 running in a virtual environment.  When I run pip install -r requirements.txt, I get the following error dump:

> ERROR: Command errored out with exit status 1:
   command: /home/mfrants/.venv/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_ostuz82/psycopg2_19f31fa63619400ca82c92fa0a9d722d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_ostuz82/psycopg2_19f31fa63619400ca82c92fa0a9d722d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zmfud3n9
       cwd: /tmp/pip-install-_ostuz82/psycopg2_19f31fa63619400ca82c92fa0a9d722d/
  Complete output (25 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-zmfud3n9/psycopg2.egg-info
  writing /tmp/pip-pip-egg-info-zmfud3n9/psycopg2.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-zmfud3n9/psycopg2.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-zmfud3n9/psycopg2.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-zmfud3n9/psycopg2.egg-info/SOURCES.txt'
  /opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
    warnings.warn(msg)
  
  Error: pg_config executable not found.
  
  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:
  
      python setup.py build_ext --pg-config /path/to/pg_config build ...
  
  or with the pg_config option in 'setup.cfg'.
  
  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

I installed psycopg2-binary (version 2.8.5) but am still getting the same error.

**Comment by servilla** [comment]
Hi @mfrants

I've updated the deployment environment to use the latest versions of package dependencies, but you will still need to either install pg_config or replace `psycopg2` with `psycopg2-binary` in both the `requirements.txt` and `setup.py` files. As mentioned in the README, I use Anaconda3 as my default Python development environment and it comes with `pg_config` pre-installed, along with `psycopg2` being available in their library.

Also, you will need to use at least Python 3.8.

Mark

**Comment by servilla** [comment]
Marina Frants:
